/*
 * Estos datos de proba foron xerados usando ChatGPT 3.5 en Abril de 2024
 * e posteriormente editados.
 */
export const MUNICIPIOS = [
	{
		"id": 15030,
		"nome": "A Coruña",
		"provincia": "A Coruña",
		"habitantes": 215227,
		"km_cadrados": 37.83,
		"imaxe_src": "https://upload.wikimedia.org/wikipedia/commons/e/eb/A_coruna_torre_de_hercules_sunset_edit.jpg",
		"imaxe_url": "https://commons.wikimedia.org/wiki/File:A_coruna_torre_de_hercules_sunset_edit.jpg",
		"imaxe_autor": "Alessio Damato, CC BY-SA 3.0 <http://creativecommons.org/licenses/by-sa/3.0/>, via Wikimedia Commons",
	},
	{
		"id": 15056,
		"nome": "Oleiros",
		"provincia": "A Coruña",
		"habitantes": 34979,
		"km_cadrados": 48.1,
		"imaxe_src": "https://upload.wikimedia.org/wikipedia/commons/f/f5/Praia_de_Portocovo_e_castelo_de_Santa_Cruz.JPG",
		"imaxe_url": "https://commons.wikimedia.org/wiki/File:Praia_de_Portocovo_e_castelo_de_Santa_Cruz.JPG",
		"imaxe_autor": "Vilachan, CC BY-SA 3.0 <https://creativecommons.org/licenses/by-sa/3.0>, via Wikimedia Commons",
	},
	{
		"id": 15057,
		"nome": "Carballo",
		"provincia": "A Coruña",
		"habitantes": 31252,
		"km_cadrados": 208.8,
		"imaxe_src": "https://upload.wikimedia.org/wikipedia/commons/d/d4/Praia-e-porto-razo-carballo.jpg",
		"imaxe_url": "https://commons.wikimedia.org/wiki/File:Praia-e-porto-razo-carballo.jpg",
		"imaxe_autor": "Chorima1, CC BY-SA 3.0 <https://creativecommons.org/licenses/by-sa/3.0>, via Wikimedia Commons",
	},
	{
		"id": 15078,
		"nome": "Santiago de Compostela",
		"provincia": "A Coruña",
		"habitantes": 95092,
		"km_cadrados": 220.0,
		"imaxe_src": "https://upload.wikimedia.org/wikipedia/commons/c/cf/2010-Catedral_de_Santiago_de_Compostela-Galicia_%28Spain%29_4.jpg",
		"imaxe_url": "https://commons.wikimedia.org/wiki/File:2010-Catedral_de_Santiago_de_Compostela-Galicia_(Spain)_4.jpg",
		"imaxe_autor": "Luis Miguel Bugallo Sánchez, CC BY-SA 3.0 <https://creativecommons.org/licenses/by-sa/3.0>, via Wikimedia Commons",
	},
	{
		"id": 15054,
		"nome": "Ferrol",
		"provincia": "A Coruña",
		"habitantes": 66060,
		"km_cadrados": 82.0,
		"imaxe_src": "https://upload.wikimedia.org/wikipedia/commons/9/93/Ferrol-021.jpg",
		"imaxe_url": "https://commons.wikimedia.org/wiki/File:Ferrol-021.jpg",
		"imaxe_autor": "Basilio, CC BY-SA 3.0 <http://creativecommons.org/licenses/by-sa/3.0/>, via Wikimedia Commons",
	},
	{
		"id": 15055,
		"nome": "Narón",
		"provincia": "A Coruña",
		"habitantes": 39624,
		"km_cadrados": 73.3,
		"imaxe_src": "https://upload.wikimedia.org/wikipedia/commons/2/27/Casa_do_Concello_de_Naron.jpg",
		"imaxe_url": "https://commons.wikimedia.org/wiki/File:Casa_do_Concello_de_Naron.jpg",
		"imaxe_author": "The original uploader was PepedoCouto at Galician Wikipedia.(Original text: PepedoCouto), CC BY-SA 3.0 <http://creativecommons.org/licenses/by-sa/3.0/>, via Wikimedia Commons",
	},
	{
		"id": 15020,
		"nome": "Culleredo",
		"provincia": "A Coruña",
		"habitantes": 30310,
		"km_cadrados": 37.4,
		"imaxe_src": "https://upload.wikimedia.org/wikipedia/commons/0/08/Culleredo-Iglesia_del_Burgo_03.jpg",
		"imaxe_url": "https://commons.wikimedia.org/wiki/File:Culleredo-Iglesia_del_Burgo_03.jpg",
		"imaxe_autor": "Oilisab, CC BY-SA 4.0 <https://creativecommons.org/licenses/by-sa/4.0>, via Wikimedia Commons",
	},
	{
		"id": 15025,
		"nome": "Fene",
		"provincia": "A Coruña",
		"habitantes": 15412,
		"km_cadrados": 48.1,
		"imaxe_src": "https://upload.wikimedia.org/wikipedia/commons/1/1a/Orgullo_Petrolero_Pemex_BAP_Navantia_Ferrol.jpg",
		"imaxe_url": "https://commons.wikimedia.org/wiki/File:Orgullo_Petrolero_Pemex_BAP_Navantia_Ferrol.jpg",
		"imaxe_autor": "Nemigo, CC0, via Wikimedia Commons",
	},
	{
		"id": 15015,
		"nome": "Arteixo",
		"provincia": "A Coruña",
		"habitantes": 31786,
		"km_cadrados": 93.7,
		"imaxe_src": "https://upload.wikimedia.org/wikipedia/commons/7/7e/Sede_de_inditex_arteixo.jpg",
		"imaxe_url": "https://commons.wikimedia.org/wiki/File:Sede_de_inditex_arteixo.jpg",
		"imaxe_autor": "Nemigo, Public domain, via Wikimedia Commons",
	},
	{
		"id": 15032,
		"nome": "Abegondo",
		"provincia": "A Coruña",
		"habitantes": 7166,
		"km_cadrados": 77.7,
		"imaxe_src": "https://upload.wikimedia.org/wikipedia/commons/1/15/Encoro_Abegondo_Cecebre_14.jpg",
		"image_url": "https://commons.wikimedia.org/wiki/File:Encoro_Abegondo_Cecebre_14.jpg",
		"imaxe_autor": "Miguel Branco, CC BY-SA 4.0 <https://creativecommons.org/licenses/by-sa/4.0>, via Wikimedia Commons",
	},
	{
		"id": 36038,
		"nome": "Pontevedra",
		"provincia": "Pontevedra",
		"habitantes": 82872,
		"km_cadrados": 118.3,
		"imaxe_src": "https://upload.wikimedia.org/wikipedia/commons/d/d9/R%C3%ADo_L%C3%A9rez%2C_Pontevedra.JPG",
		"imaxe_url": "https://commons.wikimedia.org/wiki/File:R%C3%ADo_L%C3%A9rez,_Pontevedra.JPG",
		"imaxe_autor": "Bene Riobó, CC BY-SA 2.5 ES <https://creativecommons.org/licenses/by-sa/2.5/es/deed.en>, via Wikimedia Commons"
	},
	{
		"id": 36057,
		"nome": "Vigo",
		"provincia": "Pontevedra",
		"habitantes": 294997,
		"km_cadrados": 109.06,
		"imaxe_src": "https://upload.wikimedia.org/wikipedia/commons/f/fa/Ponte_de_Rande%2C_Vigo.JPG",
		"imaxe_url": "https://commons.wikimedia.org/wiki/File:Ponte_de_Rande,_Vigo.JPG",
		"imaxe_autor": "Peregrina.pintos, CC BY-SA 4.0 <https://creativecommons.org/licenses/by-sa/4.0>, via Wikimedia Commons",
	},
	{
		"id": 36016,
		"nome": "Marín",
		"provincia": "Pontevedra",
		"habitantes": 25025,
		"km_cadrados": 23.2,
		"imaxe_src": "https://upload.wikimedia.org/wikipedia/commons/1/14/Muelle_de_reparaciones_-_panoramio.jpg",
		"imaxe_url": "https://commons.wikimedia.org/wiki/File:Muelle_de_reparaciones_-_panoramio.jpg",
		"imaxe_autor": "manpeloura, CC BY-SA 3.0 <https://creativecommons.org/licenses/by-sa/3.0>, via Wikimedia Commons",
	},
	{
		"id": 36039,
		"nome": "Ponteareas",
		"provincia": "Pontevedra",
		"habitantes": 22978,
		"km_cadrados": 67.5,
		"imaxe_src": "https://upload.wikimedia.org/wikipedia/commons/f/f8/Penedo%2C_Ponteareas.jpg",
		"imaxe_url": "https://commons.wikimedia.org/wiki/File:Penedo,_Ponteareas.jpg",
		"imaxe_autor": "Edu, CC BY 2.0 <https://creativecommons.org/licenses/by/2.0>, via Wikimedia Commons",
	},
	{
		"id": 36916,
		"nome": "Sanxenxo",
		"provincia": "Pontevedra",
		"habitantes": 17541,
		"km_cadrados": 44.8,
		"imaxe_src": "https://upload.wikimedia.org/wikipedia/commons/2/2b/Sanxenxo_desde_Portonovo_01-02r.jpg",
		"imaxe_url": "https://commons.wikimedia.org/wiki/File:Sanxenxo_desde_Portonovo_01-02r.jpg",
		"imaxe_autor": "Lameiro, CC BY-SA 4.0 <https://creativecommons.org/licenses/by-sa/4.0>, via Wikimedia Commons",
	},
	{
		"id": 36020,
		"nome": "Vilagarcía de Arousa",
		"provincia": "Pontevedra",
		"habitantes": 37247,
		"km_cadrados": 37.2,
		"imaxe_src": "https://upload.wikimedia.org/wikipedia/commons/9/9a/Guindastres_e_embarcaci%C3%B3n_no_porto_de_Vilagarc%C3%ADa_de_Arousa._Galiza-V21.jpg",
		"imaxe_url": "https://commons.wikimedia.org/wiki/File:Guindastres_e_embarcaci%C3%B3n_no_porto_de_Vilagarc%C3%ADa_de_Arousa._Galiza-V21.jpg",
		"imaxe_autor": "Luis Miguel Bugallo Sánchez (Lmbuga), CC BY-SA 3.0 <https://creativecommons.org/licenses/by-sa/3.0>, via Wikimedia Commons",
	},
	{
		"id": 36055,
		"nome": "Redondela",
		"provincia": "Pontevedra",
		"habitantes": 29889,
		"km_cadrados": 52.9,
		"imaxe_src": "https://upload.wikimedia.org/wikipedia/commons/c/ca/Viaduto_de_Pontevedra%2C_Redondela.jpg",
		"imaxe_url": "https://commons.wikimedia.org/wiki/File:Viaduto_de_Pontevedra,_Redondela.jpg",
		"imaxe_autor": "Xavier Rodríguez, CC BY 2.0 <https://creativecommons.org/licenses/by/2.0>, via Wikimedia Commons",
	},
	{
		"id": 36017,
		"nome": "Moaña",
		"provincia": "Pontevedra",
		"habitantes": 17109,
		"km_cadrados": 21.3,
		"imaxe_src": "https://upload.wikimedia.org/wikipedia/commons/0/03/Igrexa_de_San_Marti%C3%B1o_de_Moa%C3%B1a.jpg",
		"imaxe_url": "https://commons.wikimedia.org/wiki/File:Igrexa_de_San_Marti%C3%B1o_de_Moa%C3%B1a.jpg",
		"imaxe_autor": "Bene Riobó, CC BY-SA 4.0 <https://creativecommons.org/licenses/by-sa/4.0>, via Wikimedia Commons",
	},
	{
		"id": 36043,
		"nome": "A Estrada",
		"provincia": "Pontevedra",
		"habitantes": 21168,
		"km_cadrados": 175.1,
		"imaxe_src": "https://upload.wikimedia.org/wikipedia/commons/a/a6/Xardins_do_Pazo_de_Oca%2C_A_Estrada_%285151387546%29.jpg",
		"imaxe_url": "https://commons.wikimedia.org/wiki/File:Xardins_do_Pazo_de_Oca,_A_Estrada_(5151387546).jpg",
		"imaxe_autor": "amaianos from Galicia, CC BY 2.0 <https://creativecommons.org/licenses/by/2.0>, via Wikimedia Commons",
	},
	{
		"id": 36019,
		"nome": "Cangas",
		"provincia": "Pontevedra",
		"habitantes": 25708,
		"km_cadrados": 38.1,
		"imaxe_src": "https://upload.wikimedia.org/wikipedia/commons/d/d8/Cangas._Galiza-3.jpg",
		"imaxe_url": "https://commons.wikimedia.org/wiki/File:Cangas._Galiza-3.jpg",
		"imaxe_autor": "Luis Miguel Bugallo Sánchez (Lmbuga), CC BY-SA 3.0 <https://creativecommons.org/licenses/by-sa/3.0>, via Wikimedia Commons"
	},

	{
		"id": 32054,
		"nome": "Ourense",
		"provincia": "Ourense",
		"habitantes": 105233,
		"km_cadrados": 85.0,
		"imaxe_src": "https://upload.wikimedia.org/wikipedia/commons/6/6b/Praza_Maior%2C_Ourense.jpg",
		"imaxe_url": "https://commons.wikimedia.org/wiki/File:Praza_Maior,_Ourense.jpg",
		"imaxe_autor": "Dario Alvarez",
	},
	{
		"id": 32013,
		"nome": "O Carballiño",
		"provincia": "Ourense",
		"habitantes": 14201,
		"km_cadrados": 50.4,
		"imaxe_src": "https://upload.wikimedia.org/wikipedia/commons/d/dd/2016_Templo_da_Vera_Cruz._Carballi%C3%B1o_01.jpg",
		"imaxe_url": "https://commons.wikimedia.org/wiki/File:2016_Templo_da_Vera_Cruz._Carballi%C3%B1o_01.jpg",
		"imaxe_autor": "Luis Miguel Bugallo Sánchez (Lmbuga), CC BY-SA 4.0 <https://creativecommons.org/licenses/by-sa/4.0>, via Wikimedia Commons",
	},
	{
		"id": 32024,
		"nome": "O Barco de Valdeorras",
		"provincia": "Ourense",
		"habitantes": 13294,
		"km_cadrados": 200.0,
		"imaxe_src": "https://upload.wikimedia.org/wikipedia/commons/5/52/O_Barco_de_Valdeorras.jpg",
		"imaxe_url": "https://commons.wikimedia.org/wiki/File:O_Barco_de_Valdeorras.jpg",
		"imaxe_autor": "Estevoaei, CC BY-SA 4.0 <https://creativecommons.org/licenses/by-sa/4.0>, via Wikimedia Commons",
	},
	{
		"id": 32003,
		"nome": "Allariz",
		"provincia": "Ourense",
		"habitantes": 6083,
		"km_cadrados": 66.8,
		"imaxe_src": "https://upload.wikimedia.org/wikipedia/commons/8/8c/R%C3%ADo_Arnoia_-_Allariz_A32.jpg",
		"imaxe_url": "https://commons.wikimedia.org/wiki/File:R%C3%ADo_Arnoia_-_Allariz_A32.jpg",
		"imaxe_autor": "Luis Miguel Bugallo Sánchez (Lmbuga), CC BY-SA 3.0 <https://creativecommons.org/licenses/by-sa/3.0>, via Wikimedia Commons",
	},
	{
		"id": 27028,
		"nome": "Lugo",
		"provincia": "Lugo",
		"habitantes": 98007,
		"km_cadrados": 332.2,
		"imaxe_src": "https://upload.wikimedia.org/wikipedia/commons/e/ed/Muralla_romana_de_Lugo_18.jpg",
		"imaxe_url": "https://commons.wikimedia.org/wiki/File:Muralla_romana_de_Lugo_18.jpg",
		"imaxe_autor": "Simon Burchell, CC BY-SA 4.0 <https://creativecommons.org/licenses/by-sa/4.0>, via Wikimedia Commons",
	},
	{
		"id": 27052,
		"nome": "Monforte de Lemos",
		"provincia": "Lugo",
		"habitantes": 18210,
		"km_cadrados": 199.9,
		"imaxe_src": "https://upload.wikimedia.org/wikipedia/commons/1/1b/Monforte_Los_escolapios_-_panoramio.jpg",
		"imaxe_url": "https://commons.wikimedia.org/wiki/File:Monforte_Los_escolapios_-_panoramio.jpg",
		"imaxe_autor": "farrangallo, CC BY-SA 3.0 <https://creativecommons.org/licenses/by-sa/3.0>, via Wikimedia Commons",
	},
	{
		"id": 27058,
		"nome": "Sarria",
		"provincia": "Lugo",
		"habitantes": 12619,
		"km_cadrados": 194.7,
		"imaxe_src": "https://upload.wikimedia.org/wikipedia/commons/f/fb/Sarria-Fortaleza_de_Sarria.jpg",
		"imaxe_url": "https://commons.wikimedia.org/wiki/File:Sarria-Fortaleza_de_Sarria.jpg",
		"imaxe_autor": "Archivo histórico de sarria, CC BY-SA 3.0 <https://creativecommons.org/licenses/by-sa/3.0>, via Wikimedia Commons",
	},
	{
		"id": 27056,
		"nome": "Ribadeo",
		"provincia": "Lugo",
		"habitantes": 9990,
		"km_cadrados": 107.6,
		"imaxe_src": "https://upload.wikimedia.org/wikipedia/commons/b/b0/Marina_y_puente_los_santos_-_ribadeo_-_panoramio.jpg",
		"imaxe_url": "https://commons.wikimedia.org/wiki/File:Marina_y_puente_los_santos_-_ribadeo_-_panoramio.jpg",
		"imaxe_autor": "2008dago21, CC BY-SA 3.0 <https://creativecommons.org/licenses/by-sa/3.0>, via Wikimedia Commons",
	},
	{
		"id": 27016,
		"nome": "Chantada",
		"provincia": "Lugo",
		"habitantes": 10928,
		"km_cadrados": 294.4,
		"imaxe_src": "https://upload.wikimedia.org/wikipedia/commons/1/1d/Belesar_3.JPG",
		"imaxe_url": "https://commons.wikimedia.org/wiki/File:Belesar_3.JPG",
		"imaxe_autor": "Graña, CC BY-SA 3.0 <https://creativecommons.org/licenses/by-sa/3.0>, via Wikimedia Commons",
	},
	{
		"id": 27036,
		"nome": "Lourenzá",
		"provincia": "Lugo",
		"habitantes": 2900,
		"km_cadrados": 154.5,
		"imaxe_src": "https://upload.wikimedia.org/wikipedia/commons/e/e9/Monasterio_de_San_Salvador_de_Lourenz%C3%A1.jpg",
		"imaxe_url": "https://commons.wikimedia.org/wiki/File:Monasterio_de_San_Salvador_de_Lourenz%C3%A1.jpg",
		"imaxe_autor": "José Antonio Gil Martínez, CC BY 2.0 <https://creativecommons.org/licenses/by/2.0>, via Wikimedia Commons",
	},
	{
		"id": 27041,
		"nome": "Mondoñedo",
		"provincia": "Lugo",
		"habitantes": 4648,
		"km_cadrados": 178.9,
		"imaxe_src": "https://upload.wikimedia.org/wikipedia/commons/b/b0/Mondo%C3%B1edo_Cathedral_2021_-_exterior_2.jpg",
		"imaxe_url": "https://commons.wikimedia.org/wiki/File:Mondo%C3%B1edo_Cathedral_2021_-_exterior_2.jpg",
		"imaxe_autor": "Fernando Pascullo, CC BY-SA 4.0 <https://creativecommons.org/licenses/by-sa/4.0>, via Wikimedia Commons",
	},
	{
		"id": 27046,
		"nome": "Pantón",
		"provincia": "Lugo",
		"habitantes": 4474,
		"km_cadrados": 167.7,
		"imaxe_src": "https://upload.wikimedia.org/wikipedia/commons/3/33/Puente_sobre_Sil_entre_Santo_Estevo_de_Ribas_do_Sil_e_Pant%C3%B3n.jpg",
		"imaxe_url": "https://commons.wikimedia.org/wiki/File:Puente_sobre_Sil_entre_Santo_Estevo_de_Ribas_do_Sil_e_Pant%C3%B3n.jpg",
		"imaxe_autor": "Angel, CC BY-SA 2.0 <https://creativecommons.org/licenses/by-sa/2.0>, via Wikimedia Commons",
	},
	{
		"id": 27059,
		"nome": "Sober",
		"provincia": "Lugo",
		"habitantes": 3061,
		"km_cadrados": 149.0,
		"imaxe_src": "https://upload.wikimedia.org/wikipedia/commons/8/8e/Doade%2C_Sober%2C_Galiza.jpg",
		"imaxe_url": "https://commons.wikimedia.org/wiki/File:Doade,_Sober,_Galiza.jpg",
		"imaxe_autor": "Ramon Piñeiro, CC BY-SA 2.0 <https://creativecommons.org/licenses/by-sa/2.0>, via Wikimedia Commons",
	},
];

export const PROVINCIAS = [
	{ value: 'A Coruña', label: 'A Coruña' },
	{ value: 'Lugo', label: 'Lugo' },
	{ value: 'Ourense', label: 'Ourense' },
	{ value: 'Pontevedra', label: 'Pontevedra' },
];
